version: 0.2
env:
  variables:
    EKS_CLUSTER_NAME: java-eks-app-eks-cluster
    AWS_REGION: us-east-1
    REPOSITORY_URI: 891062950211.dkr.ecr.us-east-1.amazonaws.com/java-eks-app-java-app
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - echo Build started on `date`
      - echo Installing Helm...
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - echo Compiling the JAVA app...
      - mvn clean package


  build:
    commands: 
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Updating kubeconfig....
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
      - echo "Caller Identity:"
      - aws sts get-caller-identity
      - echo Deploying with Helm...
      - helm upgrade --install java-eks-app-java ./terraform-infra/modules/helm-charts/java-app --namespace default --set image.repository=$REPOSITORY_URI,image.tag=latest 
      - echo Build completed on `date`

